import '../assets/scss/variables/index.scss';
import '../assets/scss/core/index.scss';
import '../assets/scss/commons/index.scss';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

const fontFamily = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={fontFamily.className}>{children}</body>
    </html>
  );
}
