import '../assets/scss/variables/index.scss';
import '../assets/scss/core/index.scss';
import '../assets/scss/navigation/index.scss';
import '../assets/scss/atoms/index.scss';
import '../assets/scss/commons/index.scss';
import '../assets/scss/containers/index.scss';
import '../assets/scss/transitions/index.scss';

import { type ReactNode } from 'react';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import Sidebar from '~/components/navigation/contents/Sidebar';
import { SidebarProvider } from '~/components/navigation/context/SidebarProvider';
import ReactQueryProvider from '~/components/queries/ReactQueryProvider';
import { ToastProvider } from '~/atoms/Toast/context/ToastProvider';

const fontFamily = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={fontFamily.className}>
        <ToastProvider>
          <SidebarProvider>
            <Sidebar />
          </SidebarProvider>
          <ReactQueryProvider>
            <div className='pl-5'>{children}</div>
          </ReactQueryProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
